version: '1.0'

services:

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    command: --max-connections=500
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password 
      MYSQL_DATABASE: benchbase
    ports:
      - "3307:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql

  mysql-ui:
    container_name: mysql-ui
    hostname: mysql-ui
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8888:80"

# volumes:
#   mysql-data:  
